apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.6
    helm:
      releaseName: jenkins

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated: {}
